### ISSUE TITLE
Creating different python scripts

### ISSUE THREAD

**Issue by ismailbhinder** [UBC-MDS/DSCI522-2425-group31_age-group-prediction#58]
Make the following python scripts

- [x] Download/extract data

- [x] Clean/transform data

- [x] Split and pre-process data

- [x] Exploratory data analysis

- [x] Also update readme so that the user can see how to run these fie

**Comment by Rashidikn1** [comment]
Done with the tasks. Anyone can review and merge

**Comment by ismailbhinder** [comment]
This issue was addressed by #71 pull request.
