### ISSUE TITLE
create functions separate files (save in src folder), and write tests for those functions(save in test folder)

### ISSUE THREAD

**Issue by DongchunChen** [UBC-MDS/DSCI522-2425-group31_age-group-prediction#83]
5 functions need to be done:
- [x] write_csv
- [x] #86
- [x] #88
- [x] #87
- [x] #89

- [x] add README.md under test folder, update Root README.md as well.
- [x] tests for each function needs to be done with [pytest](https://docs.pytest.org/en/7.0.x/) Python package framework. Tests will live in a test directory, with files/subdirectories organized as per the testing framework you are using.

**Comment by ismailbhinder** [comment]
I'll do this #87

**Comment by sienko** [comment]
I am looking into this: https://github.com/UBC-MDS/DSCI522-2425-group31_age-group-prediction/issues/86

**Comment by ismailbhinder** [comment]
We actually do not need to do this #88

**Comment by Rashidikn1** [comment]
Done with #89
