### ISSUE TITLE
create CHANGELOG.md

### ISSUE THREAD

**Issue by DongchunChen** [UBC-MDS/DSCI522-2425-group31_age-group-prediction#91]
In this file describe any improvements you made to the project based on feedback, and point to evidence of these improvements. You can point us to evidence of addressing it by providing URLs to reference specific lines of code, commit messages, pull requests, etc. Be sure to add some narration when sharing these URLs so that it is easy for us to identify which changes to your work addressed which pieces of feedback.

- [x] list all the comments we address and paste the commits URL under

**Comment by sienko** [comment]
Done
