### ISSUE TITLE
Description of Features

### ISSUE THREAD

**Issue by ismailbhinder** [UBC-MDS/DSCI522-2425-group31_age-group-prediction#94]
"As mentioned I liked all the figure provided, however it wasn't clear to me what the features all are in your data. For example, the feature 'oral', I'm not certain to what this refers?" -Peer Reviewer

- [ ] I will add the description of each feature in the quarto document

**Comment by sienko** [comment]
I found a description of the oral feature and added it to the metadata file along with all the other fields. These are now included in the report c50401ae9c8b039205f5750774df3a05c89500ba
